title: Sathish Manthani # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About Me:
  <br>
  I work as data engineer. I’m also a graduate student at Bellevue University pursuing my Masters in Data Science. 
  I have good experience in building data pipelines. I’m passionate about building scalable, reliable, and maintainable data applications.
  <br><br>
  Connect with me:
  <br>
  <a href="https://www.linkedin.com/in/sathishmanthani/"><img src="images/linkedin.png" data-canonical-src="images/linkedin.png" width="75" height="75" /></a>
  <a href="https://github.com/sathishmanthani"><img src="images/github.png" data-canonical-src="images/Github.png" width="75" height="75" /></a>
  <a href="https://medium.com/@sathish.manthani"><img src="images/medium.png" data-canonical-src="images/Email.png" width="75" height="75" /></a>  

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
